# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pii_detector_pb2 as pii__detector__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pii_detector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PIIDetectorStub(object):
    """PIIDetector — сервис обнаружения персональных данных в тексте.
    Go backend отправляет один batch с несколькими независимыми chunks,
    ML возвращает найденные сущности. ML не создаёт токены и не знает
    глобальные offsets — финальные токены, глобальные offsets, дедупликацию
    и merge выполняет Go backend.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectBatch = channel.unary_unary(
                '/alpha_proxy.ml.v1.PIIDetector/DetectBatch',
                request_serializer=pii__detector__pb2.DetectBatchRequest.SerializeToString,
                response_deserializer=pii__detector__pb2.DetectBatchResponse.FromString,
                _registered_method=True)


class PIIDetectorServicer(object):
    """PIIDetector — сервис обнаружения персональных данных в тексте.
    Go backend отправляет один batch с несколькими независимыми chunks,
    ML возвращает найденные сущности. ML не создаёт токены и не знает
    глобальные offsets — финальные токены, глобальные offsets, дедупликацию
    и merge выполняет Go backend.
    """

    def DetectBatch(self, request, context):
        """DetectBatch — unary метод обработки одного batch с несколькими
        независимыми chunks текста.

        Общие ошибки всего RPC (не отдельных chunks):
        INVALID_ARGUMENT — сломана структура всего batch (например, пустой
        batch_id или пустой список chunks).
        RESOURCE_EXHAUSTED — очередь ML переполнена. В этом случае ML не
        возвращает частичный обычный ответ, а завершает
        весь RPC ошибкой.
        UNAVAILABLE — ML временно недоступен.
        DEADLINE_EXCEEDED — превышен deadline запроса.

        Ошибки отдельных chunks передаются через ChunkErrorCode внутри
        ChunkResult, а не через статус RPC. Backend передаёт deadline, и ML
        должно прекращать работу при отмене context. gRPC не возвращает HTTP 429
        — этим занимается внешний HTTP слой.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PIIDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectBatch,
                    request_deserializer=pii__detector__pb2.DetectBatchRequest.FromString,
                    response_serializer=pii__detector__pb2.DetectBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alpha_proxy.ml.v1.PIIDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alpha_proxy.ml.v1.PIIDetector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PIIDetector(object):
    """PIIDetector — сервис обнаружения персональных данных в тексте.
    Go backend отправляет один batch с несколькими независимыми chunks,
    ML возвращает найденные сущности. ML не создаёт токены и не знает
    глобальные offsets — финальные токены, глобальные offsets, дедупликацию
    и merge выполняет Go backend.
    """

    @staticmethod
    def DetectBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alpha_proxy.ml.v1.PIIDetector/DetectBatch',
            pii__detector__pb2.DetectBatchRequest.SerializeToString,
            pii__detector__pb2.DetectBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
